revert migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -446,13 +446,13 @@ jobs:
             URL="${API_URL}/api/status"
             echo "$(curl -I ${URL})"
             echo "${URL}"
+            exit 1
             if curl -s ${URL} | grep "ok"
               then
                 exit 0
               else
                 exit 1
             fi
-                exit 1
 
       - revert-migrations
 
@@ -516,49 +516,49 @@ jobs:
 workflows:
   default:
     jobs:
-      - build-frontend
+      # - build-frontend
 
-      - build-backend
+      # - build-backend
 
-      - test-frontend:
-          requires: [build-frontend]
+      # - test-frontend:
+      #     requires: [build-frontend]
 
-      - test-backend:
-          requires: [build-backend]
+      # - test-backend:
+      #     requires: [build-backend]
 
-      - scan-backend:
-          requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
 
-      - scan-frontend:
-          requires: [build-frontend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
 
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [main]
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     filters:
+      #       branches:
+      #         only: [main]
 
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
 
-      - run-migrations:
-          requires: [configure-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
 
-      - deploy-frontend:
-          requires: [run-migrations]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
 
-      - deploy-backend:
-          requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
 
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      - smoke-test
+          # requires: [deploy-backend, deploy-frontend]
 
-      - cloudfront-update:
-          context: slack-siren
-          requires: [smoke-test]
+#       - cloudfront-update:
+#           context: slack-siren
+#           requires: [smoke-test]
 
-      - cleanup:
-          requires: [cloudfront-update]
+#       - cleanup:
+#           requires: [cloudfront-update]
 
 
 
